// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARIyIfWqMUmZBn6h6yNqE93c9q765fD4Y',
    appId: '1:1009684567423:web:72319aa89238b4c714b64a',
    messagingSenderId: '1009684567423',
    projectId: 'catface-notify',
    authDomain: 'catface-notify.firebaseapp.com',
    storageBucket: 'catface-notify.firebasestorage.app',
    measurementId: 'G-V9TLSG63SG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlcZuOwWsifJuYm-bVnBukImR6YHrBln4',
    appId: '1:1009684567423:android:ca52866846190fa914b64a',
    messagingSenderId: '1009684567423',
    projectId: 'catface-notify',
    storageBucket: 'catface-notify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDytMh9wQcA4BxcPov2Dockh4ZRM9kG4ak',
    appId: '1:1009684567423:ios:a01aff076bedbdb314b64a',
    messagingSenderId: '1009684567423',
    projectId: 'catface-notify',
    storageBucket: 'catface-notify.firebasestorage.app',
    iosBundleId: 'com.example.catfaceProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDytMh9wQcA4BxcPov2Dockh4ZRM9kG4ak',
    appId: '1:1009684567423:ios:a01aff076bedbdb314b64a',
    messagingSenderId: '1009684567423',
    projectId: 'catface-notify',
    storageBucket: 'catface-notify.firebasestorage.app',
    iosBundleId: 'com.example.catfaceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARIyIfWqMUmZBn6h6yNqE93c9q765fD4Y',
    appId: '1:1009684567423:web:b904dcd1325e1e8014b64a',
    messagingSenderId: '1009684567423',
    projectId: 'catface-notify',
    authDomain: 'catface-notify.firebaseapp.com',
    storageBucket: 'catface-notify.firebasestorage.app',
    measurementId: 'G-M3PV83VBZQ',
  );
}
